INSERT INTO roles (name) VALUES ('PENDING_USER') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('RESIDENT') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT (name) DO NOTHING;